import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { FileContextProvider } from "./file-context";
import { Header } from "@/components/header";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { MainBreadCrumbs } from "./main-breadcrumbs";
import { Suspense } from "react";
import { ProjectHeader } from "@/components/project/project-header";

const lato = Lato({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ide,
  issues,
}: Readonly<{
  children: React.ReactNode;
  ide: React.ReactNode;
  issues: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main className="p-[25px] h-screen bg-[#0D0F11] text-white flex flex-col gap-4 ">
          <FileContextProvider>
            <Header />
            <MainBreadCrumbs />
            <Suspense>
              <div className=" flex flex-col flex-1 bg-[#191D23] px-4 py-3 rounded max-h-[max-content] overflow-scroll">
                <ProjectHeader />
                {children}
                <div className="flex mt-3 gap-3 max-w-full flex-1">
                  {ide}
                  {issues}
                </div>
              </div>
            </Suspense>
          </FileContextProvider>
        </main>
      </body>
    </html>
  );
}
