import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FileContextProvider } from "./file-context";
import { Header } from "@/components/header";
import { Breadcrumbs } from "@/components/breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-[25px] h-screen bg-[#0D0F11] text-white flex flex-col ">
          <FileContextProvider>
            <Header />
            <Breadcrumbs />
            {children}
          </FileContextProvider>
        </main>
      </body>
    </html>
  );
}
